apiVersion: v1
kind: Secret
metadata:
  name: tomcat-secret
data:
  tribes_encryption: QUVTIGlzIHRoZSB3YXk=
  db_password: c2Fwd2QK
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tomcat-config
data:
  DB_URL: "jdbc:derby://db.default.svc.cluster.local:1527/sewadb"
  DB_USERNAME: sa
