apiVersion: v1
kind: Secret
metadata:
  name: tomcat-secret
data:
  tribes-encryption: QUVTIGlzIHRoZSB3YXk=
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tomcat-config
data:
  DB_URL: "jdbc:derby://db.default.svc.cluster.local:1527/sewadb"
  DB_USERNAME: sa
  DB_PASSWORD: sapwd
