apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
spec:
  ingressClassName: nginx
  tls:
  - secretName: tls-key
  rules:
  - host: tomcat.jtips.local
    http:
      paths:
      - path: /msg
        pathType: Prefix
        backend:
          service:
            name: tomcat0
            port:
              number: 8080
