name: tomcat
services:
  db:
    image: jtips/derby
  nginx:
    image: nginx
    ports:
      - 1080:80
    volumes:
      - ../nginx/default-single.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on: [tomcat0]
  tomcat0:
    image: jtips/tomcat
    deploy:
      replicas: 3
      resources:
        limits:
          memory: 256M
          cpus: 2
    environment:
      SERVICE_BINDING_ROOT: /run
    env_file: tomcat.env
    secrets:
    - db_password
secrets:
   db_password:
     file: db-password.txt