name: tomcat
services:
  nginx:
    image: nginx
    ports:
      - 1080:80
    volumes:
      - ../nginx/default-single.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on: [tomcat0]
  tomcat0:
    image: jtips/tomcat:backup
    deploy:
      replicas: 3
      resources:
        limits:
          memory: 256M
          cpus: 2
    env_file: tomcat.env