name: tomcat
services:
  nginx:
    image: nginx
    ports:
      - 1080:80
    volumes:
      - ../nginx/default-three.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on: [tomcat1,tomcat2,tomcat3]
  tomcat1:
    image: jtips/tomcat:static
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: 2
  tomcat2:
    extends: tomcat1
  tomcat3:
    extends: tomcat1
